### ISSUE TITLE
I think this doesn't work when 26st is on Sunday

### ISSUE THREAD

**Issue by jeroenvisser101** [zenry/salary#1]
When sunday, `@salary_date.working_day?` will be false, but actually 1 day before it will also be false, no?

**Comment by zenry** [comment]
test it then :dancers:

**Comment by zenry** [comment]
I mean it works but you need to see it to believe it :8ball:

**Comment by jeroenvisser101** [comment]
Seen my PR?

**Comment by jeroenvisser101** [comment]
It has #swag
